-- ============================================================
-- Snowflake Grants Script for Database: FIRE_TEST
-- Schemas: STAGING, INTERMEDIATE, MART
-- ============================================================

-- ============================================================
-- ROLE: NAM_ONENAV_BUSINESS
-- Access: SELECT on current and future VIEWS only
-- ============================================================

-- Database access
GRANT USAGE ON DATABASE FIRE_TEST TO ROLE NAM_ONENAV_BUSINESS;

-- Schema access + current/future views
GRANT USAGE ON SCHEMA FIRE_TEST.STAGING                    TO ROLE NAM_ONENAV_BUSINESS;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIRE_TEST.STAGING      TO ROLE NAM_ONENAV_BUSINESS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIRE_TEST.STAGING   TO ROLE NAM_ONENAV_BUSINESS;

GRANT USAGE ON SCHEMA FIRE_TEST.INTERMEDIATE                    TO ROLE NAM_ONENAV_BUSINESS;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIRE_TEST.INTERMEDIATE      TO ROLE NAM_ONENAV_BUSINESS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIRE_TEST.INTERMEDIATE   TO ROLE NAM_ONENAV_BUSINESS;

GRANT USAGE ON SCHEMA FIRE_TEST.MART                    TO ROLE NAM_ONENAV_BUSINESS;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIRE_TEST.MART      TO ROLE NAM_ONENAV_BUSINESS;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIRE_TEST.MART   TO ROLE NAM_ONENAV_BUSINESS;


-- ============================================================
-- ROLE: NAM_ONENAV_BUSINESSANALYST
-- Access: SELECT on current and future VIEWS and TABLES
-- ============================================================

-- Database access
GRANT USAGE ON DATABASE FIRE_TEST TO ROLE NAM_ONENAV_BUSINESSANALYST;

-- Schema access + current/future tables & views
GRANT USAGE ON SCHEMA FIRE_TEST.STAGING                     TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FIRE_TEST.STAGING      TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIRE_TEST.STAGING   TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIRE_TEST.STAGING       TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIRE_TEST.STAGING    TO ROLE NAM_ONENAV_BUSINESSANALYST;

GRANT USAGE ON SCHEMA FIRE_TEST.INTERMEDIATE                     TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FIRE_TEST.INTERMEDIATE      TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIRE_TEST.INTERMEDIATE   TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIRE_TEST.INTERMEDIATE       TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIRE_TEST.INTERMEDIATE    TO ROLE NAM_ONENAV_BUSINESSANALYST;

GRANT USAGE ON SCHEMA FIRE_TEST.MART                     TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FIRE_TEST.MART      TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIRE_TEST.MART   TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA FIRE_TEST.MART       TO ROLE NAM_ONENAV_BUSINESSANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FIRE_TEST.MART    TO ROLE NAM_ONENAV_BUSINESSANALYST;


-- ============================================================
-- ROLE: NAM_ONENAV_DEVELOPER
-- Access: Read + Write on all current and future objects
-- ============================================================

-- Database access
GRANT USAGE ON DATABASE FIRE_TEST TO ROLE NAM_ONENAV_DEVELOPER;

-- Schema access (full) + all current/future objects
GRANT ALL PRIVILEGES ON SCHEMA FIRE_TEST.STAGING TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FIRE_TEST.STAGING          TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FIRE_TEST.STAGING       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FIRE_TEST.STAGING           TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FIRE_TEST.STAGING        TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FIRE_TEST.STAGING          TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA FIRE_TEST.STAGING       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FIRE_TEST.STAGING       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA FIRE_TEST.STAGING    TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA FIRE_TEST.STAGING    TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA FIRE_TEST.STAGING TO ROLE NAM_ONENAV_DEVELOPER;

GRANT ALL PRIVILEGES ON SCHEMA FIRE_TEST.INTERMEDIATE TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FIRE_TEST.INTERMEDIATE          TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FIRE_TEST.INTERMEDIATE       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FIRE_TEST.INTERMEDIATE           TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FIRE_TEST.INTERMEDIATE        TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FIRE_TEST.INTERMEDIATE          TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA FIRE_TEST.INTERMEDIATE       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FIRE_TEST.INTERMEDIATE       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA FIRE_TEST.INTERMEDIATE    TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA FIRE_TEST.INTERMEDIATE    TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA FIRE_TEST.INTERMEDIATE TO ROLE NAM_ONENAV_DEVELOPER;

GRANT ALL PRIVILEGES ON SCHEMA FIRE_TEST.MART TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FIRE_TEST.MART          TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FIRE_TEST.MART       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FIRE_TEST.MART           TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FIRE_TEST.MART        TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FIRE_TEST.MART          TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA FIRE_TEST.MART       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FIRE_TEST.MART       TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA FIRE_TEST.MART    TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA FIRE_TEST.MART    TO ROLE NAM_ONENAV_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA FIRE_TEST.MART TO ROLE NAM_ONENAV_DEVELOPER;


-- ============================================================
-- ROLE: NAM_ONENAV_OPERATOR
-- Access: Read + Write on all current and future objects
-- ============================================================

-- Database access
GRANT USAGE ON DATABASE FIRE_TEST TO ROLE NAM_ONENAV_OPERATOR;

-- Schema access (full) + all current/future objects
GRANT ALL PRIVILEGES ON SCHEMA FIRE_TEST.STAGING TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FIRE_TEST.STAGING          TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FIRE_TEST.STAGING       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FIRE_TEST.STAGING           TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FIRE_TEST.STAGING        TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FIRE_TEST.STAGING          TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA FIRE_TEST.STAGING       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FIRE_TEST.STAGING       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA FIRE_TEST.STAGING    TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA FIRE_TEST.STAGING    TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA FIRE_TEST.STAGING TO ROLE NAM_ONENAV_OPERATOR;

GRANT ALL PRIVILEGES ON SCHEMA FIRE_TEST.INTERMEDIATE TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FIRE_TEST.INTERMEDIATE          TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FIRE_TEST.INTERMEDIATE       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FIRE_TEST.INTERMEDIATE           TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FIRE_TEST.INTERMEDIATE        TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FIRE_TEST.INTERMEDIATE          TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA FIRE_TEST.INTERMEDIATE       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FIRE_TEST.INTERMEDIATE       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA FIRE_TEST.INTERMEDIATE    TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA FIRE_TEST.INTERMEDIATE    TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA FIRE_TEST.INTERMEDIATE TO ROLE NAM_ONENAV_OPERATOR;

GRANT ALL PRIVILEGES ON SCHEMA FIRE_TEST.MART TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FIRE_TEST.MART          TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA FIRE_TEST.MART       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA FIRE_TEST.MART           TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA FIRE_TEST.MART        TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL STAGES IN SCHEMA FIRE_TEST.MART          TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN SCHEMA FIRE_TEST.MART       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FIRE_TEST.MART       TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE SEQUENCES IN SCHEMA FIRE_TEST.MART    TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN SCHEMA FIRE_TEST.MART    TO ROLE NAM_ONENAV_OPERATOR;
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN SCHEMA FIRE_TEST.MART TO ROLE NAM_ONENAV_OPERATOR;
